spring:
  application:
    name: plan-service
  config:
    import: "optional:configserver:http://3.109.184.195:8888"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

