spring:
  application:
    name: plan-service
  config:
    import: "optional:configserver:http://3.111.235.72:8888"
  kafka:
    producer:
      bootstrap-servers: 65.1.243.55:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

